spring:
  application:
    name: search-engine-llm

  ai:
    openai:
      api-key: KEY
    base-url: http://127.0.0.1:11434/
    chat:
      options:
        model: deepseek-r1:7b




lucene:
  indexLibrary: D:/Lucenedemo/indexLibrary